### ISSUE TITLE
Comparison with `std::sync::Mutex`

### ISSUE THREAD

**Issue by jjant** [ncomendant/wasm_mutex#1]
From reading the readme, it's not clear to me why I would pick this over `std::sync::Mutex`.

**Comment by ncomendant** [comment]
Thank you for the feedback. I am not sure how to improve the wording on the readme, and I'm open to suggestions. Here is the relevant section as it stands currently:

> Data stored in a RefCell<T> encounter a BorrowError or BorrowMutError when multiple closures attempt to access the same data simulatenously (e.g. a click event handler and a set interval handler). Similarly, a std::sync::Mutex will panic under the same circumstances, due to calling lock while the lock is already being held by the current thread. wasm_mutex::Mutex will allow the data to be locked and unlocked, allowing single access to the data at any given time.

In short, `std::sync::Mutex` will panic when a closure attempts to lock the mutex if it is already being locked elsewhere.
